new Vue({
  el: "#app",
  data: {
    articles: [
      {
        id: 0,
        imgSrc: "./img/Photo_6.png",
        imgAlt: "Photo_6",
        style: "Kitchan Design",
        title: "Let’s Get Solution For Building Construction Work",
        date: "26 December,2022",
        href: "#",
      },
      {
        id: 1,
        imgSrc: "./img/Photo_7.png",
        imgAlt: "Photo_7",
        style: "Living Design",
        title: "Low Cost Latest Invented Interior Designing Ideas.",
        date: "22 December,2022",
        href: "#",
      },
      {
        id: 2,
        imgSrc: "./img/Photo_8.png",
        imgAlt: "Photo_8",
        style: "Interior Design",
        title: "Best For Any Office & Business Interior Solution",
        date: "25 December,2022",
        href: "#",
      },
      {
        id: 3,
        imgSrc: "./img/Photo_11.png",
        imgAlt: "Photo_11",
        style: "Kitchan Design",
        title: "Let’s Get Solution For Building Construction Work",
        date: "26 December,2022 ",
        href: "#",
      },
      {
        id: 4,
        imgSrc: "./img/Photo_12.png",
        imgAlt: "Photo_12",
        style: "Living Design",
        title: "Low Cost Latest Invented Interior Designing Ideas.",
        date: "22 December,2022 ",
        href: "#",
      },
      {
        id: 5,
        imgSrc: "./img/Photo_13.png",
        imgAlt: "Photo_13",
        style: "Interior Design",
        title: "Best For Any Office & Business Interior Solution",
        date: "25 December,2022",
        href: "#",
      },
    ],
  },
});
